apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rock
  region: us-east-1
  version: "1.27"

managedNodeGroups:
  - name: rock-ng-1
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    volumeSize: 50
    instanceTypes: ["t3a.large"]
    spot: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        albIngress: true
        certManager: true
    privateNetworking: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true

  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true

  - metadata:
      name: autoscaler-service
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

  - metadata:
      name: external-secrets
      namespace: external-secrets
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "secretsmanager:GetRandomPassword"
        - "secretsmanager:GetResourcePolicy"
        - "secretsmanager:GetSecretValue"
        - "secretsmanager:DescribeSecret"
        - "secretsmanager:ListSecretVersionIds"
        - "secretsmanager:ListSecrets"
        Resource: '*'

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: false
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single

addons:
  - name: "vpc-cni"
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest